export const CORTES = [
  { value: "10", label: "C.A. de Arica" },
  { value: "11", label: "C.A. de Iquique" },
  { value: "15", label: "C.A. de Antofagasta" },
  { value: "20", label: "C.A. de Copiapó" },
  { value: "25", label: "C.A. de La Serena" },
  { value: "30", label: "C.A. de Valparaíso" },
  { value: "35", label: "C.A. de Rancagua" },
  { value: "40", label: "C.A. de Talca" },
  { value: "45", label: "C.A. de Chillan" },
  { value: "46", label: "C.A. de Concepción" },
  { value: "50", label: "C.A. de Temuco" },
  { value: "55", label: "C.A. de Valdivia" },
  { value: "56", label: "C.A. de Puerto Montt" },
  { value: "60", label: "C.A. de Coyhaique" },
  { value: "61", label: "C.A. de Punta Arenas" },
  { value: "90", label: "C.A. de Santiago" },
  { value: "91", label: "C.A. de San Miguel" },
];
