export const CORTES = {
  "C.A. de Arica": "10",
  "C.A. de Iquique": "11",
  "C.A. de Antofagasta": "15",
  "C.A. de Copiapó": "20",
  "C.A. de La Serena": "25",
  "C.A. de Valparaíso": "30",
  "C.A. de Rancagua": "35",
  "C.A. de Talca": "40",
  "C.A. de Chillan": "45",
  "C.A. de Concepción": "46",
  "C.A. de Temuco": "50",
  "C.A. de Valdivia": "55",
  "C.A. de Puerto Montt": "56",
  "C.A. de Coyhaique": "60",
  "C.A. de Punta Arenas": "61",
  "C.A. de Santiago": "90",
  "C.A. de San Miguel": "91",
};
