export const TRIBUNALES = {
  "1º Juzgado de Letras de Arica": "2",
  "1º Juzgado De Letras de Arica ex 4°": "1400",
  "2º Juzgado de Letras de Arica": "3",
  "2º Juzgado De Letras de Arica ex 4°": "1401",
  "3º Juzgado de Letras de Arica": "4",
  "3º Juzgado de Letras de Arica Ex 4º": "5",
  "Juzgado de Letras y Gar. Pozo Almonte": "6",
  "1º Juzgado de Letras de Iquique": "9",
  "2º Juzgado de Letras de Iquique": "10",
  "3º Juzgado de Letras de Iquique": "11",
  "Juzgado de Letras Tocopilla": "13",
  "Juzgado de Letras y Gar.de María Elena": "14",
  "1º Juzgado de Letras de Calama": "16",
  "2º Juzgado de Letras de Calama": "17",
  "3º Juzgado de Letras de Calama": "658",
  "Juzgado de Letras y Gar. de Taltal": "26",
  "1º Juzgado de Letras Civil de Antofagasta": "1041",
  "2º Juzgado de Letras Civil de Antofagasta": "1042",
  "3º Juzgado de Letras Civil de Antofagasta": "1043",
  "4 ° Juzgado de Letras Civil de Antofagasta": "1044",
  "Juzgado de Letras y Garantía Mejillones": "1501",
  "Juzgado de Letras y Gar. de Chañaral": "27",
  "Juzgado de Letras de Diego de Almagro": "29",
  "1º Juzgado de Letras de Copiapó": "31",
  "2º Juzgado de Letras de Copiapó": "32",
  "3º Juzgado de Letras de Copiapó": "33",
  "Juzgado de Letras y Gar.de Freirina": "34",
  "4º Juzgado de Letras de Copiapó": "926",
  "1º Juzgado de Letras de Vallenar": "36",
  "2º Juzgado de Letras de Vallenar": "37",
  "Juzgado de Letras y Gar.de Caldera": "386",
  "1º Juzgado de Letras de la Serena": "40",
  "2º Juzgado de Letras de la Serena": "41",
  "3º Juzgado de Letras de la Serena": "42",
  "1º Juzgado de Letras de Coquimbo": "43",
  "2º Juzgado de Letras de Coquimbo": "44",
  "3º Juzgado de Letras de Coquimbo": "45",
  "Juzgado de Letras de Vicuña": "46",
  "Juzgado de letras y garantía de Andacollo": "47",
  "1º Juzgado de Letras de Ovalle": "48",
  "2º Juzgado de Letras de Ovalle": "49",
  "3º Juzgado de Letras de Ovalle": "50",
  "Juzgado de Letras y Gar.de Combarbalá": "51",
  "Juzgado de Letras de Illapel": "52",
  "Juzgado de Letras y Gar. de los Vilos": "53",
  "1º Juzgado Civil de Valparaíso": "56",
  "2º Juzgado Civil de Valparaíso": "55",
  "3º Juzgado Civil de Valparaíso": "54",
  "4º Juzgado Civil de Valparaíso": "59",
  "5º Juzgado Civil de Valparaíso": "60",
  "1º Juzgado Civil de Viña del Mar": "57",
  "2º Juzgado Civil de Viña del Mar": "58",
  "3º Juzgado Civil de Viña del Mar": "61",
  "1º Juzgado de Letras de Quilpue": "83",
  "2º Juzgado de Letras de Quilpue": "84",
  "Juzgado de Letras de Villa Alemana": "85",
  "Juzgado de Letras de Casablanca": "86",
  "Juzgado de Letras de La Ligua": "87",
  "Juzgado de Letras y Gar. de Petorca": "88",
  "1º Juzgado de Letras de Los Andes": "89",
  "2º Juzgado de Letras de Los Andes": "90",
  "1º Juzgado de Letras de San Felipe": "92",
  "1º Juzgado de Letras de San Felipe Ex 2º": "93",
  "Juzgado de Letras y Gar.de Putaendo": "94",
  "1º Juzgado de Letras de Quillota": "96",
  "2º Juzgado de Letras de Quillota": "97",
  "Juzgado de Letras de La Calera": "98",
  "Juzgado de Letras de Limache": "99",
  "1º Juzgado de Letras de San Antonio": "101",
  "2º Juzgado de Letras de San Antonio": "102",
  "Juzgado de Letras y Gar. de Isla de Pascua": "103",
  "Juzgado de Letras y Gar.de Quintero": "660",
  "1º Juzgado Civil de Rancagua": "110",
  "2º Juzgado Civil de Rancagua": "969",
  "1º Juzgado de Letras de Rengo": "111",
  "Juzgado de Letras de San Vicente de Tagua Tagua": "113",
  "1º Juzgado de Letras y Gar.de Peumo": "114",
  "1º Juzgado de Letras de San Fernando": "115",
  "2º Juzgado de Letras de San Fernando": "116",
  "1º Juzgado de Letras de Santa Cruz": "117",
  "1º Juzgado De Letras De Santa Cruz Ex 2°": "118",
  "Juzgado de Letras y Gar.de Pichilemu": "119",
  "Juzgado de Letras y Gar.de Litueche": "1150",
  "Juzgado de Letras y Gar.de Peralillo": "1151",
  "1º Juzgado de Letras de Talca": "122",
  "2º Juzgado de Letras de Talca": "123",
  "3º Juzgado de Letras de Talca": "124",
  "4º Juzgado de Letras de Talca": "125",
  "Juzgado de Letras de Constitución": "126",
  "Juzgado De Letras Y Gar. de Curepto": "127",
  "1º Juzgado de Letras de Curicó": "129",
  "2º Juzgado de Letras de Curicó": "130",
  "2º Juzgado de Letras de Curicó Ex 3°": "131",
  "Juzgado De Letras Y Gar. de Licantén": "132",
  "Juzgado de Letras de Molina": "133",
  "1º Juzgado de Letras de Linares": "135",
  "2º Juzgado de Letras de Linares": "136",
  "Juzgado de Letras de San Javier": "138",
  "Juzgado de Letras de Cauquenes": "139",
  "Juzgado de Letras y Gar. de Chanco": "140",
  "Juzgado de Letras de Parral": "141",
  "1º Juzgado Civil de Chillán": "145",
  "2º Juzgado Civil de Chillán": "146",
  "1º Juzgado de Letras de San Carlos": "147",
  "Juzgado de Letras de Yungay": "149",
  "Juzgado de Letras y Gar. de Bulnes": "150",
  "Juzgado de Letras y Gar.de Coelemu": "151",
  "Juzgado de Letras y Gar.de Quirihue": "152",
  "1º Juzgado de Letras de Los Angeles": "154",
  "2º Juzgado de Letras de Los Angeles": "155",
  "2° Juzgado de Letras de Los Angeles ex 3°": "156",
  "Juzgado de Letras y Gar. de Mulchen": "157",
  "Juzgado de Letras y Gar.de Nacimiento": "158",
  "Juzgado de Letras y Gar.de Laja": "159",
  "Juzgado de Letras y Gar.de Yumbel": "160",
  "1º Juzgado Civil de Concepción": "161",
  "2º Juzgado Civil de Concepción": "162",
  "3º Juzgado Civil de Concepción": "163",
  "1º Juzgado Civil de Talcahuano": "179",
  "2º Juzgado Civil de Talcahuano": "180",
  "Juzgado de Letras de Tomé": "187",
  "Juzgado de Letras y Gar.de Florida": "188",
  "Juzgado de Letras y Gar.de Santa Juana": "189",
  "Juzgado de Letras y Gar. de Lota": "190",
  "1º Juzgado de Letras de Coronel": "191",
  "2º Juzgado de Letras de Coronel": "192",
  "Juzgado de Letras y Gar.de Lebu": "193",
  "Juzgado de Letras de Arauco": "194",
  "Juzgado de Letras y Gar.de Curanilahue": "195",
  "Juzgado de Letras de Cañete": "196",
  "Juzgado de Letras y Gar. Santa Bárbara": "385",
  "Juzgado de Letras y Gar.de Cabrero": "1152",
  "1º Juzgado Civil de Temuco": "197",
  "2º Juzgado Civil de Temuco": "198",
  "Juzgado de Letras de Angol": "204",
  "Juzgado de Letras y Gar.de Collipulli": "206",
  "Juzgado de Letras y Gar.de Traiguén": "207",
  "Juzgado de Letras de Victoria": "208",
  "Juzgado de Letras y Gar.de Curacautin": "209",
  "Juzgado de Letras Loncoche": "210",
  "Juzgado de Letras de Pitrufquen": "211",
  "Juzgado de Letras de Villarrica": "212",
  "Juzgado de Letras de Nueva Imperial": "213",
  "Juzgado de Letras y Gar.de Pucón": "214",
  "Juzgado de Letras de Lautaro": "215",
  "Juzgado de Letras y Gar.de Carahue": "216",
  "3º Juzgado Civil de Temuco": "406",
  "Juzgado de Letras y Gar.de Tolten": "946",
  "Juzgado de Letras y Gar.de Puren": "947",
  "1º Juzgado Civil de Valdivia": "220",
  "2º Juzgado Civil de Valdivia": "221",
  "Juzgado de Letras de Mariquina": "222",
  "Juzgado de Letras y Gar.de Paillaco": "223",
  "Juzgado de Letras Los Lagos": "224",
  "Juzgado de Letras y Gar. de Panguipulli": "225",
  "Juzgado de Letras y Gar.de la Unión": "226",
  "Juzgado de Letras y Gar.de Río Bueno": "227",
  "1º Juzgado de Letras de Osorno": "229",
  "2º Juzgado de Letras de Osorno": "230",
  "Juzgado de Letras de Rio Negro": "233",
  "1º Juzgado Civil de Puerto Montt": "237",
  "2º Juzgado Civil de Puerto Montt": "1012",
  "Juzgado de Letras de Puerto Varas": "238",
  "Juzgado de Letras y Gar.de Calbuco": "240",
  "Juzgado de Letras y Gar. de Maullin": "241",
  "Juzgado de Letras de Castro": "242",
  "Juzgado de Letras de Ancud": "243",
  "Juzgado de Letras y Garantía de Achao": "244",
  "Juzgado de Letras y Gar. de Chaitén": "245",
  "Juzgado de Letras y Gar. de Los Muermos": "659",
  "Juzgado de Letras y Gar. de Quellón": "662",
  "Juzgado de Letras y Gar. de Hualaihue": "1013",
  "1º Juzgado de Letras de Coyhaique": "246",
  "1º Juzgado de Letras de Coyhaique Ex 2º": "247",
  "Juzgado de Letras y Gar.de pto.Aysen": "248",
  "Juzgado de Letras y Gar.de Chile Chico": "249",
  "Juzgado de Letras y Gar.de Cochrane": "250",
  "Juzgado de Letras y Gar.de Puerto Cisnes": "996",
  "1º Juzgado de Letras de Punta Arenas": "253",
  "2º Juzgado de Letras de Punta Arenas": "254",
  "3º Juzgado de Letras de Punta Arenas": "255",
  "Juzgado de Letras y Gar. de Puerto Natales": "257",
  "Juzgado de Letras y Gar.de Porvenir": "258",
  "Juzgado de Letras y Garantía de Cabo de Hornos": "1502",
  "1º Juzgado Civil de Santiago": "259",
  "2º Juzgado Civil de Santiago": "260",
  "3º Juzgado Civil de Santiago": "261",
  "4º Juzgado Civil de Santiago": "262",
  "5º Juzgado Civil de Santiago": "263",
  "6º Juzgado Civil de Santiago": "264",
  "7º Juzgado Civil de Santiago": "265",
  "8º Juzgado Civil de Santiago": "266",
  "9º Juzgado Civil de Santiago": "267",
  "10º Juzgado Civil de Santiago": "268",
  "11º Juzgado Civil de Santiago": "269",
  "12º Juzgado Civil de Santiago": "270",
  "13º Juzgado Civil de Santiago": "271",
  "14º Juzgado Civil de Santiago": "272",
  "15º Juzgado Civil de Santiago": "273",
  "16º Juzgado Civil de Santiago": "274",
  "17º Juzgado Civil de Santiago": "275",
  "18º Juzgado Civil de Santiago": "276",
  "19º Juzgado Civil de Santiago": "277",
  "20º Juzgado Civil de Santiago": "278",
  "21º Juzgado Civil de Santiago": "279",
  "22º Juzgado Civil de Santiago": "280",
  "23º Juzgado Civil de Santiago": "281",
  "24º Juzgado Civil de Santiago": "282",
  "25º Juzgado Civil de Santiago": "283",
  "26º Juzgado Civil de Santiago": "284",
  "27º Juzgado Civil de Santiago": "285",
  "28º Juzgado Civil de Santiago": "286",
  "29º Juzgado Civil de Santiago": "287",
  "30º Juzgado Civil de Santiago": "288",
  "Juzgado de Letras de Colina": "387",
  "1º Juzgado Civil de San Miguel": "343",
  "2º Juzgado Civil de San Miguel": "344",
  "3º Juzgado Civil de San Miguel": "345",
  "4º Juzgado Civil de San Miguel": "390",
  "1º Juzgado Civil de Puente Alto": "364",
  "1º Juzgado De Letras De Talagante": "373",
  "2º Juzgado De Letras De Talagante": "374",
  "1º Juzgado de Letras de Melipilla": "375",
  "1º Juzgado de Letras de Buin": "377",
  "2º Juzgado de Letras de Buin": "378",
  "Juzgado de Letras de Peñaflor": "388",
  "1º Juzgado de Letras de San Bernardo": "400",
  "1º Juzgado de Letras de San Bernardo Ex 3°": "1402",
  "2º Juzgado de Letras de San Bernardo": "401",
  "2º Juzgado de Letras de San Bernardo Ex 3°": "1403",
};
